export default function AlertsPage() {
  return (
    <div className="space-y-14 text-gray-300">

      {/* Title */}
      <div>
        <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-4">
          Alerting & Incident Management
        </h1>
        <p className="text-gray-400 leading-relaxed">
          Alertmanager processes alerts generated by Prometheus and ensures
          timely notification and incident visibility across the system.
        </p>
      </div>

      {/* Alert Flow */}
      <div>
        <h2 className="text-2xl font-bold text-[#E50914] mb-4">
          Alert Flow Architecture
        </h2>

        <img
          src="/images/alert-flow.png"
          alt="Alert Flow"
          className="rounded-2xl border border-gray-800 shadow-xl mb-6"
        />

        <div className="bg-black border border-gray-800 rounded-xl p-6 font-mono text-sm text-gray-400">
{`Metric Threshold Breached
        ↓
Prometheus Alert Rule
        ↓
Alertmanager
        ↓
Notification Channel (Email / Slack / etc)`}
        </div>
      </div>

      {/* Alert Rules */}
      <div>
        <h2 className="text-2xl font-bold text-[#E50914] mb-4">
          Prometheus Alert Rules
        </h2>

        <div className="bg-black border border-gray-800 rounded-xl p-6 font-mono text-sm text-gray-400">
{`groups:
- name: application-alerts
  rules:
  - alert: HighCPUUsage
    expr: sum(rate(container_cpu_usage_seconds_total[5m])) > 0.8
    for: 2m
    labels:
      severity: critical`}
        </div>

        <p className="mt-6 text-gray-400 leading-relaxed">
          Alert rules define threshold conditions and severity levels
          to trigger incident notifications automatically.
        </p>
      </div>

      {/* Notification Channels */}
      <div>
        <h2 className="text-2xl font-bold text-[#E50914] mb-4">
          Notification Channels
        </h2>

        <img
          src="/images/alertmanager-config.png"
          alt="Alertmanager Config"
          className="rounded-2xl border border-gray-800 shadow-xl mb-6"
        />

        <ul className="space-y-3 list-disc list-inside text-gray-400">
          <li>Email notifications</li>
          <li>Slack integration</li>
          <li>Webhook integrations</li>
          <li>Severity-based routing</li>
        </ul>
      </div>

      {/* Logging Integration */}
      <div>
        <h2 className="text-2xl font-bold text-[#E50914] mb-4">
          Logging & Troubleshooting
        </h2>

        <p className="text-gray-400 leading-relaxed">
          Alerts are correlated with centralized logs to enable rapid
          root cause analysis. Logs from application pods and cluster
          components are aggregated for investigation.
        </p>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-[#E50914] mb-4">
          Incident Handling Strategy
        </h2>

        <ul className="space-y-3 list-disc list-inside text-gray-400">
          <li>Threshold-based alerting</li>
          <li>Severity classification (warning / critical)</li>
          <li>Escalation rules</li>
          <li>Post-incident review & monitoring refinement</li>
        </ul>
      </div>

    </div>
  );
}
